### ISSUE TITLE
Leaking HKEY's?

### ISSUE THREAD

**Issue by jeffbargmann** [prnayjain/NightLightTray#1]
https://github.com/prnayjain/NightLightTray/blob/35629845dd170bdb83a90a7be34df547e97be959/NightLightTray.cpp#L406

Just a heads up, RegCloseKey is not being called here and in a number of other return-early cases. Thanks for your work!

**Comment by prnayjain** [comment]
Thanks for reporting! Fixed with commit https://github.com/prnayjain/NightLightTray/commit/177c1ebc9890cb138156f2e873d2ce7c977d47ef
